#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101411_BP

#include "Basic.hpp"

#include "PyAbility_101411_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101411_BP.Ability_101411_BP_C
// 0x0000 (0x3B30 - 0x3B30)
class UAbility_101411_BP_C final : public UPyAbility_101411
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101411_BP_C">();
	}
	static class UAbility_101411_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101411_BP_C>();
	}
};
static_assert(alignof(UAbility_101411_BP_C) == 0x000010, "Wrong alignment on UAbility_101411_BP_C");
static_assert(sizeof(UAbility_101411_BP_C) == 0x003B30, "Wrong size on UAbility_101411_BP_C");

}

