#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101751_BP

#include "Basic.hpp"

#include "PyAbility_101751_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101751_BP.Ability_101751_BP_C
// 0x0000 (0x2B50 - 0x2B50)
class UAbility_101751_BP_C final : public UPyAbility_101751
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101751_BP_C">();
	}
	static class UAbility_101751_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101751_BP_C>();
	}
};
static_assert(alignof(UAbility_101751_BP_C) == 0x000008, "Wrong alignment on UAbility_101751_BP_C");
static_assert(sizeof(UAbility_101751_BP_C) == 0x002B50, "Wrong size on UAbility_101751_BP_C");

}

