#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_102082_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102082_BP.Ability_102082_BP_C
// 0x0000 (0x2E88 - 0x2E88)
class UAbility_102082_BP_C final : public UAbility_134_Fly
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102082_BP_C">();
	}
	static class UAbility_102082_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102082_BP_C>();
	}
};
static_assert(alignof(UAbility_102082_BP_C) == 0x000008, "Wrong alignment on UAbility_102082_BP_C");
static_assert(sizeof(UAbility_102082_BP_C) == 0x002E88, "Wrong size on UAbility_102082_BP_C");

}

