#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101462_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyAbility_101462_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101462_BP.Ability_101462_BP_C
// 0x0008 (0x2A90 - 0x2A88)
class UAbility_101462_BP_C final : public UPyAbility_101462
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2A88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Ability_101462_BP(int32 EntryPoint);
	void SetAbilityExtraWidget_1(class UUserWidget* InExtraWidget);
	void SetAbilityStatusWidget_1(class UUserWidget* InUserWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101462_BP_C">();
	}
	static class UAbility_101462_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101462_BP_C>();
	}
};
static_assert(alignof(UAbility_101462_BP_C) == 0x000008, "Wrong alignment on UAbility_101462_BP_C");
static_assert(sizeof(UAbility_101462_BP_C) == 0x002A90, "Wrong size on UAbility_101462_BP_C");
static_assert(offsetof(UAbility_101462_BP_C, UberGraphFrame) == 0x002A88, "Member 'UAbility_101462_BP_C::UberGraphFrame' has a wrong offset!");

}

