#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101861_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Hero_1018_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101861_BP.Ability_101861_BP_C
// 0x0010 (0x2BD0 - 0x2BC0)
class UAbility_101861_BP_C final : public UAbility_101861
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2BC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Ability_101861_BP(int32 EntryPoint);
	void SetAbilityExtraWidget_1(class UUserWidget* InExtraWidget);
	void SetAbilityStatusWidget_1(class UUserWidget* InUserWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101861_BP_C">();
	}
	static class UAbility_101861_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101861_BP_C>();
	}
};
static_assert(alignof(UAbility_101861_BP_C) == 0x000010, "Wrong alignment on UAbility_101861_BP_C");
static_assert(sizeof(UAbility_101861_BP_C) == 0x002BD0, "Wrong size on UAbility_101861_BP_C");
static_assert(offsetof(UAbility_101861_BP_C, UberGraphFrame) == 0x002BC0, "Member 'UAbility_101861_BP_C::UberGraphFrame' has a wrong offset!");

}

