#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_102292_BP

#include "Basic.hpp"

#include "Hero_Synergy_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102292_BP.Ability_102292_BP_C
// 0x0000 (0x3328 - 0x3328)
class UAbility_102292_BP_C final : public UAbility_100021
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102292_BP_C">();
	}
	static class UAbility_102292_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102292_BP_C>();
	}
};
static_assert(alignof(UAbility_102292_BP_C) == 0x000008, "Wrong alignment on UAbility_102292_BP_C");
static_assert(sizeof(UAbility_102292_BP_C) == 0x003328, "Wrong size on UAbility_102292_BP_C");

}

