#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_102211_BP

#include "Basic.hpp"

#include "PyAbility_102211_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102211_BP.Ability_102211_BP_C
// 0x0000 (0x2A38 - 0x2A38)
class UAbility_102211_BP_C final : public UPyAbility_102211
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102211_BP_C">();
	}
	static class UAbility_102211_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102211_BP_C>();
	}
};
static_assert(alignof(UAbility_102211_BP_C) == 0x000008, "Wrong alignment on UAbility_102211_BP_C");
static_assert(sizeof(UAbility_102211_BP_C) == 0x002A38, "Wrong size on UAbility_102211_BP_C");

}

