#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101792_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101792_BP.Ability_101792_BP_C
// 0x0000 (0x2A40 - 0x2A40)
class UAbility_101792_BP_C final : public UAbility_108
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101792_BP_C">();
	}
	static class UAbility_101792_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101792_BP_C>();
	}
};
static_assert(alignof(UAbility_101792_BP_C) == 0x000008, "Wrong alignment on UAbility_101792_BP_C");
static_assert(sizeof(UAbility_101792_BP_C) == 0x002A40, "Wrong size on UAbility_101792_BP_C");

}

