#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101122_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101122_BP.Ability_101122_BP_C
// 0x0000 (0x2C98 - 0x2C98)
class UAbility_101122_BP_C final : public UAbility_113
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101122_BP_C">();
	}
	static class UAbility_101122_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101122_BP_C>();
	}
};
static_assert(alignof(UAbility_101122_BP_C) == 0x000008, "Wrong alignment on UAbility_101122_BP_C");
static_assert(sizeof(UAbility_101122_BP_C) == 0x002C98, "Wrong size on UAbility_101122_BP_C");

}

