#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101791_BP

#include "Basic.hpp"

#include "PyAbility_101791_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101791_BP.Ability_101791_BP_C
// 0x0000 (0x2B20 - 0x2B20)
class UAbility_101791_BP_C final : public UPyAbility_101791
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101791_BP_C">();
	}
	static class UAbility_101791_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101791_BP_C>();
	}
};
static_assert(alignof(UAbility_101791_BP_C) == 0x000008, "Wrong alignment on UAbility_101791_BP_C");
static_assert(sizeof(UAbility_101791_BP_C) == 0x002B20, "Wrong size on UAbility_101791_BP_C");

}

