#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_202_BP

#include "Basic.hpp"

#include "PyAbility_202_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_202_BP.Ability_202_BP_C
// 0x0000 (0x2AC0 - 0x2AC0)
class UAbility_202_BP_C final : public UPyAbility_202
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_202_BP_C">();
	}
	static class UAbility_202_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_202_BP_C>();
	}
};
static_assert(alignof(UAbility_202_BP_C) == 0x000008, "Wrong alignment on UAbility_202_BP_C");
static_assert(sizeof(UAbility_202_BP_C) == 0x002AC0, "Wrong size on UAbility_202_BP_C");

}

