#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101891_BP

#include "Basic.hpp"

#include "PyAbility_101891_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101891_BP.Ability_101891_BP_C
// 0x0000 (0x2DF0 - 0x2DF0)
class UAbility_101891_BP_C final : public UPyAbility_101891
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101891_BP_C">();
	}
	static class UAbility_101891_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101891_BP_C>();
	}
};
static_assert(alignof(UAbility_101891_BP_C) == 0x000008, "Wrong alignment on UAbility_101891_BP_C");
static_assert(sizeof(UAbility_101891_BP_C) == 0x002DF0, "Wrong size on UAbility_101891_BP_C");

}

